### ISSUE TITLE
Test and encapsulate the state management

### ISSUE THREAD

**Issue by rgolea** [near-projects/wallet-selector#107]
## Description

Add unit tests for the state management.

## Acceptance Criteria

The tests should isolate the code and allow it to be as robust as possible.

**Comment by lewis-sqa** [comment]
I'd recommend against testing state management directly as it's implementation detail.

We should test the **result of state changes** through the functionality we desire. In the wallet implementations this might be that we call `signIn` and assert `isSignedIn` now returns `true`. In React (via React Testing Library) we would test that the UI has updated to reflect the state change. Using this approach means we have the flexibility to refactor how state is handled without tests failing even if the desired functionality is working as expected.
