### ISSUE TITLE
Enhance modal UI

### ISSUE THREAD

**Issue by AmmarHumackicSQA** [near-projects/wallet-selector#11]
Related to user story #2

**Comment by AmmarHumackicSQA** [comment]
- [ ] Add new icons for wallet providers

**Comment by kujtimprenkuSQA** [comment]
Updated the css for the modal.
Added box-shadow instead of using borders when hovering over a provider.
Made borders more rounded.
Changed color for the dark mode.

**Comment by kujtimprenkuSQA** [comment]
Changed icons, added official icons for each provider and made sure they look good in both light and dark mode.

**Comment by kujtimprenkuSQA** [comment]
Updated some of the icons as requested (to use only one type of icon .png)
Managed to invert styles for the Near icon in dark mode.
