### ISSUE TITLE
Implement option to connect with NEAR Wallet using near-api-js and WalletConnection

### ISSUE THREAD

**Issue by AmmarHumackicSQA** [near-projects/wallet-selector#15]
Related to user story #5

**Comment by GentBinakuSQA** [comment]
This is done, but I need time to test properly

**Comment by GentBinakuSQA** [comment]
Review can review this code as it is finished

**Comment by GentBinakuSQA** [comment]
Amir has review my code and has found the solution to be optimal.

Moving this ticket to Reviewer Approved
