### ISSUE TITLE
Build and deploy example dApp

### ISSUE THREAD

**Issue by AmmarHumackicSQA** [near-projects/wallet-selector#17]
As suggested build and deploy new example dApp

https://near-examples.github.io/guest-book

**Comment by GentBinakuSQA** [comment]
I have designed the dApp, however it's the Near Wallet Login which is taken more than usual to do, as soon as I finish that this will be finished

**Comment by GentBinakuSQA** [comment]
I have deploy the Guest Book app and will be adding the code to the repository of Guest Book NEAR
