### ISSUE TITLE
Go through Narwallet (browser extension wallet) documentation

### ISSUE THREAD

**Issue by AmmarHumackicSQA** [near-projects/wallet-selector#20]
See if it's possible to initiate a connection to it from the wallet selector modal.

[https://github.com/Narwallets/narwallets-extension/blob/master/API-design.md](url)

**Comment by kujtimprenkuSQA** [comment]
Continued reading the documentation for the Narwallets Extension.
Based on what I've read so far I don't think it's possible to connect to the extension the way we connect with Sender wallet.
I plan continue researching this a bit more tomorrow.
