### ISSUE TITLE
Go through Ledger (hardware wallet) documentation

### ISSUE THREAD

**Issue by AmmarHumackicSQA** [near-projects/wallet-selector#21]
Identify requirements for making a connection with Ledger hard wallet device.

Resources:

[https://github.com/near/near-ledger-js](url)

[https://docs.near.org/docs/tutorials/ledger](url)

[https://blog.neufund.org/integrating-ledger-nanos-into-your-dapp-using-neufunds-js-wallet-provider-ecb71ca8f7b6](url)

[https://www.youtube.com/watch?v=V9eRdPCE2lo](url)

[https://portal.productboard.com/lnpb6dhpyz225uxhuo74d32p/c/25-support-active-ledger-transports?utm_medium=social&utm_source=portal_share](url)

[https://github.com/wandevs/wan-web-wallet/blob/master/src/wallets/ledger.ts](url)

**Comment by amirsaran3** [comment]
Researched and implemented basic Ledger connection demo

**Comment by nninkovicSQA** [comment]
Researched and found Ledger Hardware emulator that may be used for testing purpeses.

**Comment by nninkovicSQA** [comment]
Emulator documentation https://speculos.ledger.com/
