### ISSUE TITLE
Implement basic Ledger (hard wallet) connection demo

### ISSUE THREAD

**Issue by AmmarHumackicSQA** [near-projects/wallet-selector#22]
Related to user stories #23 and #24

**Comment by amirsaran3** [comment]
Implemented basic ledger wallet connection to default derivation path and pushed with new branch "task-22/implement-basic-wallet-connection"

**Comment by amirsaran3** [comment]
Finished basic ledger wallet connection through modal and option for choosing different derivation paths before connection to Ledger wallet

**Comment by mikedotexe** [comment]
seeing as it's moved to done I'm closing
