### ISSUE TITLE
Error handling for Ledger wallet provider option

### ISSUE THREAD

**Issue by AmmarHumackicSQA** [near-projects/wallet-selector#33]
Related to user stories #23 and #24

After selecting the appropriate derivation path to connect if Ledger wallet device is not found and selected from the browser pop up, display error message "Error connecting to Ledger wallet". 

Example:
![Screen Shot 2021-12-23 at 1 52 13 PM](https://user-images.githubusercontent.com/95851006/147243646-4f33d470-b260-4a1b-b033-a687af178c55.png)

**Comment by kujtimprenkuSQA** [comment]
Addded error handling for ledger wallet when no device is selected or found.
Pushed the changes and made a pull request which was merged later and the current changes are in dev branch.
Link to pull request: https://github.com/near-projects/wallet-selector/pull/32
