### ISSUE TITLE
Go through LavaMoat toolset documentation

### ISSUE THREAD

**Issue by AmmarHumackicSQA** [near-projects/wallet-selector#36]
See how to implement and use LavaMoat toolset.

https://github.com/LavaMoat/LavaMoat

**Comment by GentBinakuSQA** [comment]
This investigation has provided enough information to go and implement in our modal repo

**Comment by lewis-sqa** [comment]
My initial thoughts were that we could use this tool for whitelisting NPM scripts such as “postinstall” and running the build process via Webpack.

On further inspection, [it’s clear this tool isn’t directed at packages](https://www.youtube.com/watch?v=iaqe6F4S2tA&t=2295s) but rather applications that make use of packages. So in our case, it will be consumers of this project who should use LavaMoat (further details why are described in the link).

**Comment by lewis-sqa** [comment]
Phase 2 work. It's unlikely this project will make use of LavaMoat given the findings.
