### ISSUE TITLE
Add Support for Signing & Sending Transactions

### ISSUE THREAD

**Issue by AmmarHumackicSQA** [near-projects/wallet-selector#38]

**Comment by GentBinakuSQA** [comment]
I will adding the smart contract code located in the modal repository as per Amir suggestions

**Comment by GentBinakuSQA** [comment]
The function for SmartContract will be a contract object which will have to ability to add viewMethods and changeMethods

**Comment by GentBinakuSQA** [comment]
I have completed the implementation of SmartContract with Near and SenderWallet, however due to inability to test legder wallet I haven't yet finished it

**Comment by GentBinakuSQA** [comment]
The definition for the LedgerContract has been written, however I am blocked without the dongle to test

**Comment by GentBinakuSQA** [comment]
I think this ticket is obselete, aren't we singing transactions instead of contracts ?

**Comment by GentBinakuSQA** [comment]
I have run into an error with the Near Wallet I cant seem to access the signandSendTransaction function in the account object,
SenderWallet is done the transactions is there, I will try to figure out how to combine it with the guest book example

**Comment by GentBinakuSQA** [comment]
I have fixed the error both the NearWallet and SenderWallet will have a function called addContract in Near Wallet will expose a contract object, while SenderWallet will just use the signAndSendTransaction function

**Comment by GentBinakuSQA** [comment]
I get the following error

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'byteLength')
    at stringifyJsonOrBytes (src.e31bb0bc.js:77110:31)
    at Object.functionCall (src.e31bb0bc.js:77126:76)
    at SenderWallet.<anonymous> (src.e31bb0bc.js:81008:45)
    at step (src.e31bb0bc.js:80835:17)
    at Object.next (src.e31bb0bc.js:80766:14)
    at src.e31bb0bc.js:80738:67
    at new Promise (<anonymous>)
    at __awaiter (src.e31bb0bc.js:80717:10)
    at SenderWallet.callContract (src.e31bb0bc.js:81002:12)
    at SmartContract.<anonymous> (src.e31bb0bc.js:87401:75)
stringifyJsonOrBytes @ src.e31bb0bc.js:77110
functionCall @ src.e31bb0bc.js:77126
(anonymous) @ src.e31bb0bc.js:81008
step @ src.e31bb0bc.js:80835
(anonymous) @ src.e31bb0bc.js:80766
(anonymous) @ src.e31bb0bc.js:80738
__awaiter @ src.e31bb0bc.js:80717
SenderWallet.callContract @ src.e31bb0bc.js:81002
(anonymous) @ src.e31bb0bc.js:87401
step @ src.e31bb0bc.js:87353
(anonymous) @ src.e31bb0bc.js:87284
(anonymous) @ src.e31bb0bc.js:87256
__awaiter @ src.e31bb0bc.js:87235
SmartContract.callContract @ src.e31bb0bc.js:87391
(anonymous) @ src.e31bb0bc.js:32501
invokePassiveEffectCreate @ src.e31bb0bc.js:26817
callCallback @ src.e31bb0bc.js:7428
invokeGuardedCallbackDev @ src.e31bb0bc.js:7477
invokeGuardedCallback @ src.e31bb0bc.js:7537
flushPassiveEffectsImpl @ src.e31bb0bc.js:26899
unstable_runWithPriority @ src.e31bb0bc.js:2973
runWithPriority$1 @ src.e31bb0bc.js:14834
flushPassiveEffects @ src.e31bb0bc.js:26776
(anonymous) @ src.e31bb0bc.js:26657
workLoop @ src.e31bb0bc.js:2923
flushWork @ src.e31bb0bc.js:2897
performWorkUntilDeadline @ src.e31bb0bc.js:2663
Promise.then (async)
(anonymous) @ src.e31bb0bc.js:32501
invokePassiveEffectCreate @ src.e31bb0bc.js:26817
callCallback @ src.e31bb0bc.js:7428
invokeGuardedCallbackDev @ src.e31bb0bc.js:7477
invokeGuardedCallback @ src.e31bb0bc.js:7537
flushPassiveEffectsImpl @ src.e31bb0bc.js:26899
unstable_runWithPriority @ src.e31bb0bc.js:2973
runWithPriority$1 @ src.e31bb0bc.js:14834
flushPassiveEffects @ src.e31bb0bc.js:26776
(anonymous) @ src.e31bb0bc.js:26657
workLoop @ src.e31bb0bc.js:2923
flushWork @ src.e31bb0bc.js:2897
performWorkUntilDeadline @ src.e31bb0bc.js:2663

**Comment by GentBinakuSQA** [comment]
After meeting with Mike I search still to figure out this error, but I can't
Also add the implementation of the signAndSendTransaction with the NearWallet I seems to have a compile error
Stating that:

`Property 'signAndSendTransaction' is protected and only accessible within class 'Account' and its subclasses.ts(2445)
`

**Comment by GentBinakuSQA** [comment]
The logic behind the implementation of the transactions is now defined outside of the modal, the developer just has to pass a transaction data structure with the correct schema. In doing this much of the code for the wallet Changed, now the contract code is removed. This implementation is consistent with the LegderWallet Implementation of the call contract.

`  async callContract(transaction: any): Promise<any> {

    transaction["signerId"] = this.wallet.getAccountId()
   
  
    //@ts-ignore
    return await this.wallet.account().signAndSendTransaction({
      receiverId: transaction.receiverId,
      signerId: this.wallet.getAccountId(),
      actions: transaction.actions,

    })`

This produces an error with the following:
`index.js:52 Uncaught (in promise) Error: Class Action is missing in schema: actions.actions
    at serializeStruct (index.js:308:1)
    at serializeField (index.js:291:1)
    at index.js:272:1
    at BinaryWriter.writeArray (index.js:124:1)
    at serializeField (index.js:272:1)
    at index.js:312:1
    at Array.map (<anonymous>)
    at serializeStruct (index.js:311:1)
    at Object.serialize (index.js:334:1)
    at signTransactionObject (transaction.js:219:1)`

**Comment by mikedotexe** [comment]
Please try out this cookbook recipe, as it seems very similar to what you're trying to accomplish here
https://github.com/near/near-api-js/blob/502da8c3dfb3821220e353ec1b9b5633e02da579/examples/cookbook/utils/wrap-near.js
