### ISSUE TITLE
Caching wallet selection of the user

### ISSUE THREAD

**Issue by AmmarHumackicSQA** [near-projects/wallet-selector#39]
Caching wallet selection of the user so that it can be automatically selected for them the next time they visit dApp for a better user experience and ease of use.

Examples:

https://github.com/Web3Modal/web3modal/blob/master/src/controllers/providers.ts#:~:text=public%20setCachedProvider(id%3A%20string)%20%7B

https://docs.blocknative.com/onboard#:~:text=You%20may%20want%20to%20cache%20the%20wallet%20a%20user%20has%20selected

**Comment by lewis-sqa** [comment]
Closing as this work has already been done.
