### ISSUE TITLE
Display wallet providers based on the user's device

### ISSUE THREAD

**Issue by AmmarHumackicSQA** [near-projects/wallet-selector#41]
Display wallet providers based on the user's device and/or browser type.

Examples:

[https://docs.blocknative.com/onboard#:~:text=wallets%20will%20be%20displayed%20when%20a%20user](url)

[https://docs.blocknative.com/onboard#:~:text=a%20preferred%20wallet.-,Example,-1](url)

**Comment by amirsaran3** [comment]
Finished this task
