### ISSUE TITLE
Integrate wallet selector into Guest Book example

### ISSUE THREAD

**Issue by amirsaran3** [near-projects/wallet-selector#53]
The Guest Book example ([https://github.com/near-examples/guest-book](https://github.com/near-examples/guest-book)) currently uses just the Near Wallet for signup and to call smart contracts. We need to change that so that the user has an option to signup and call smart contracts using our near-walletselector modal. Inside the modal will be three options: Near Wallet, Sender Wallet and Ledger Hardware Wallet.

**Comment by lewis-sqa** [comment]
The plan of action in this ticket is to create an `example` directory that demonstrates how this package can be used.
