### ISSUE TITLE
Encapsulation of the near-api-js library

### ISSUE THREAD

**Issue by rgolea** [near-projects/wallet-selector#88]
In order to be more testable and have a more robust codebase, we need to make sure that, if the `near-api-js` library changes that often, we can extrapolate all the functionalities we have right now in the project and encapsulate them in a `proxy` or a `service`. This way, if the API changes, our only concern would be to update that block and it wouldn't break the entire project.

**Comment by rgolea** [comment]
At the current time, as the architecture is right at the moment, this doesn't bring any value to the project. I would postpone this for a while.

**Comment by lewis-sqa** [comment]
We no longer see a use case for encapsulating the library. Should we find this useful in the future, we can raise a ticket then. I suspect our approach will take the form of common helpers or smaller abstractions like `ProviderService`.
