### ISSUE TITLE
Implement Standardised Event Emitter

### ISSUE THREAD

**Issue by lewis-sqa** [near-projects/wallet-selector#91]
## Description

Our [current implementation](https://github.com/near-projects/wallet-selector/blob/dev/src/utils/EventHandler.ts) of an event emitter lacks the standard approach to the pub/sub problem. We should look to mimic an approach similar to Node.js to avoid introducing new concepts. A basic event emitter should support the following:

- Instance-based as they store references to subscribers and tend to be topic related (projects can have multiple "channels"). It will also make testing easier too.
- Emit events (via `.emit("<event>", data)`).
- Multiple subscribers (via `.on("<event>", handler)` or `.addEventListener("<event>", handler)`). A common extension to this method is to return a "subscription" object that contains a `.remove` method. This avoids having to maintain a reference to the handler method.
- Unsubscribe (via `.off("<event>", handler)` or `.removeEventListener("<event>", handler)`). This is really important as not calling a method like this will lead to memory leaks.

## Acceptance Criteria

- Unit tests to prove defined functionality above.
- Existing usage of `EventEmitter` is refactored to the new approach.

**Comment by GentBinakuSQA** [comment]
Moved the event code to match the design pattern that Lewis suggested. Most of the changes are at the part of the code which does call these events.
