### ISSUE TITLE
Synchronicity of the Modal

### ISSUE THREAD

**Issue by GentBinakuSQA** [near-projects/wallet-selector#99]
## Description

The current implementation of the rendering of the modal isn't quite efficient. It renders the wallets in a full swoop.
[Render Wallets](https://github.com/near-projects/wallet-selector/blob/8caa5410c45004ed7ca7d0b903605d5a8dac7481/src/controllers/WalletController.ts#L20)
This means that all the wallets are available at the time of render. Thus our init, signIn, and disconnect calls aren't synchronous and have gaps in their execution.

## Acceptance Criteria
- Lazy Loading of the wallets
- Each render should be done synchronously 
- Unit Tests

**Comment by lewis-sqa** [comment]
Yeah, so the idea is that we'll only instantiate upon wallet upon selection or if we were already logged in with it. This will become easier once view methods are outside of the wallet implementations.

**Comment by GentBinakuSQA** [comment]
Ticket put on hold, till we fix other issues

**Comment by lewis-sqa** [comment]
This task has been somewhat addressed in #124 and #120. While all the wallets are instantiated (as dictated by the `config.wallets` array), they don't have heavy start up logic anymore. The integrations defer the startup logic until they're selected (`signIn`). We've also removed the `init` event as there wasn't a real use case for it and therefore remove the bug that triggered this task.

While lazy-loading the integrations would be a great feature, it will no doubt add a lot of unnecessary complexity into a project that only supports 3 wallets so far. When the NEAR ecosystem starts to see the [same number of wallets](https://github.com/blocknative/onboard/tree/develop/src/modules/select/wallets) as other blockchains like Ethereum, this feature will start to become far more attractive as a way of reducing bloat for dApp developers. Let's open a ticket once that event occurs and keep the project as simple as possible for now 🙂
